### ISSUE TITLE
Why not use Lavalink?

### ISSUE THREAD

**Issue by NekoSakuraLucia** [Obskurath/soundhub#1]
**Let me fork your project and add the new Lavalink-related code, and I will also improve the commands by adding commands related to playing music, everything. How does that sound?**

**Comment by Obskurath** [comment]
Why not lavalink?
I did think about using it, but as it was my first time creating a discord bot i tried to stick to the basics
I actually planned to update the bot to using lavalink and upgrade the embeds

I will asign you to this issue, as a favor, try to documentate the procces via comments or something so i can learn from this.
Thanks :)

**Comment by NekoSakuraLucia** [comment]
Alright, I will start working on it right away.

**Comment by Obskurath** [comment]
Thanks
