### ISSUE TITLE
That's a question from my own heart, haha

### ISSUE THREAD

**Issue by NekoSakuraLucia** [Obskurath/soundhub#7]
#### This is just a question I'm asking. In the future, do you think we’ll switch from using JavaScript to TypeScript? If you want my recommendation, I’d say stick with JS for now, but if the project starts growing bigger, I’d suggest switching to TS to reduce complexity.

**Comment by Obskurath** [comment]
Tbh I'm still learning the basics of ts, lemme study it and then we can change it

**Comment by NekoSakuraLucia** [comment]
Alright, no problem! Whenever you're ready, just let me know. I'll help you with the change.

**Comment by Obskurath** [comment]
Btw, how did you found my repo?

**Comment by NekoSakuraLucia** [comment]
> Btw, how did you found my repo?

Oh, it showed up on my GitHub feed. (It said it was a recommended repo for me, so I clicked to check it out, and then I ended up converting the code to Lavalink until now.)

**Comment by Obskurath** [comment]
We should choose a color for the embeds, any idea?

**Comment by Obskurath** [comment]
Be sure of pulling git, i made some changes and installed dependencies
![Screenshot 2024-11-28 212521](https://github.com/user-attachments/assets/c7ecf15f-51c9-40b6-8260-284737372534)

**Comment by NekoSakuraLucia** [comment]
Sorry for the late reply, I haven't been on my computer for a few days. I just got some free time.
