### ISSUE TITLE
Encountered an issue with sending the image created by the canvas.

### ISSUE THREAD

**Issue by NekoSakuraLucia** [Obskurath/soundhub#9]
The issue occurred 3-4 days ago because we had used the command to play music multiple times, but the image wouldn't generate. It might be a problem with the code or Discord, I'm not sure. I’ve checked the code several times, but it seems the same with no issues.

**Comment by NekoSakuraLucia** [comment]
Oh, and by the way, can I ask why you haven't come back to work yet? It's been several days.

**Comment by NekoSakuraLucia** [comment]
> Sorry man, I broke up with my gf and I don't feel good, but I will be back in no time

I'm really sorry you're going through this, but I want you to know that it's normal to feel down sometimes. Take your time and everything will get better soon.

**Comment by Obskurath** [comment]
Thanks man, I just feel really broken, I miss her a lot, you don't have idea of how much I miss her 

I'm gonna get my life fixed...

**Comment by Obskurath** [comment]
Tomorrow or when I get to my house I'm gonna code again, we should start implementing typescript, I'm gonna fix the relative paths into absolute paths and create the src folder I wasn't able to make it work without it

**Comment by NekoSakuraLucia** [comment]
> Tomorrow or when I get to my house I'm gonna code again, we should start implementing typescript, I'm gonna fix the relative paths into absolute paths and create the src folder I wasn't able to make it work without it

If you want to switch to TypeScript, I can do it for you. You should rest. I'll change the code and just wait for me to open the PR and merge it.

**Comment by Obskurath** [comment]
You sure?

I'm gonna try to do it, but I don't promise anything 

I just feel bad ... 
I'm afraid that when im on the TV she might appear on some ad, and maybe in that ad she would kiss someone else ...

Fuck I hate my life

**Comment by NekoSakuraLucia** [comment]
> You sure?
> 
> I'm gonna try to do it, but I don't promise anything
> 
> I just feel bad ... I'm afraid that when im on the TV she might appear on some ad, and maybe in that ad she would kiss someone else ...
> 
> Fuck I hate my life

I understand how you feel. It's not easy to deal with those thoughts, but doing your best is enough.
